---
boldsuck:
  github: boldsuck
  reddit: boldsuck

cakewallet:
  email: "support@cakewallet.com"
  twitter: cakewallet
  website: "https://cakewallet.com/"

lza_menace:
  github: lalanza808
  twitter: lza_menace
  website: "https://lzahq.tech"

majesticbank:
  email: "info@majesticbank.so"
  website: "https://majesticbank.sc/"

ofrnxmr:
  github: nahuhh
  matrix: "@ofrnxmr:xmr.mx"

plowsof:
  github: plowsof
  matrix: "@plowsof:matrix.org"

ravfx:
  matrix: "@ravfx:xmr.mx"

rino:
  email: "support@rino.io"
  reddit: RINOwallet
  twitter: RINOwallet
  website: "https://www.rino.io/"

rucknium:
  github: Rucknium
  matrix: "@rucknium:monero.social"
  reddit: Rucknium
  website: "https://rucknium.me/"

selsta:
  github: selsta

sethforprivacy:
  email: "sethforprivacy.vqhyi@simplelogin.com"
  reddit: sethforprivacy
  twitter: sethforprivacy
  website: "https://sethforprivacy.com/"

stormycloud.org:
  email: "admin@stormycloud.org"
  website: "https://stormycloud.org/"

trocador:
  email: "mail@trocador.app"
  twitter: TrocadorApp
  website: "https://trocador.app/"

witchofthewind:
  reddit: witchofthewind

xmr.ru:
  email: "xmr.ru@protonmail.com"
  github: xmr-ru
  website: "https://xmr.ru/"
